/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/Courses/Form': RouteRecordInfo<'/admin/Courses/Form', '/admin/Courses/Form', Record<never, never>, Record<never, never>>,
    '/admin/Courses/List': RouteRecordInfo<'/admin/Courses/List', '/admin/Courses/List', Record<never, never>, Record<never, never>>,
    '/admin/Dashboard': RouteRecordInfo<'/admin/Dashboard', '/admin/Dashboard', Record<never, never>, Record<never, never>>,
    '/admin/Login': RouteRecordInfo<'/admin/Login', '/admin/Login', Record<never, never>, Record<never, never>>,
    '/admin/Register': RouteRecordInfo<'/admin/Register', '/admin/Register', Record<never, never>, Record<never, never>>,
    '/PublicCourseDetail': RouteRecordInfo<'/PublicCourseDetail', '/PublicCourseDetail', Record<never, never>, Record<never, never>>,
    '/PublicCourses': RouteRecordInfo<'/PublicCourses', '/PublicCourses', Record<never, never>, Record<never, never>>,
  }
}
